# Run this file by typing: docker-compose up -d
version: "3.9"
services:
  ui:
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
      args:
        PROJECT_DIR: "${PROJECT_DIR}"
    container_name: ui_landing
    restart: always
    environment:
      NODE_ENV: "development"
      REACT_APP_SITE_IP: "${SITE_IP}"
      PROJECT_DIR: "${PROJECT_DIR}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PATH: "/"
      VIRTUAL_PORT: "${PORT_UI}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    ports:
      - ${PORT_UI}:${PORT_UI}
    networks:
      - proxy
      - app
    volumes:
      - ./node_modules:${PROJECT_DIR}/node_modules
      - ./packages/ui:${PROJECT_DIR}/packages/ui:z
      - ./packages/shared:${PROJECT_DIR}/packages/shared:z
    command: /bin/sh -c "chmod +x ${PROJECT_DIR}/scripts/* && ${PROJECT_DIR}/scripts/ui.sh"

networks:
  proxy:
    name: nginx-proxy
    external: true
  app:
